### ISSUE TITLE
bad code in Steering2()

### ISSUE THREAD

**Issue by dpwoos** [Iainmon/altino#1]
bad code:

"value2-127" should be "value2=127"
"value1=-127" should be "value2=-127"

so:

void Steering2(int value1, int value2)
{
	if(value1>127)
		value1=127;
	if(value2>127)
		value2-127;
	if(value1<-127)
		value1=-127;
	if(value2<-127)
		value1=-127;
	if(value1<0)
		value1=128-value1;
	if(value2<0)
		value2=128-value2;

	Sendbuf[5] = (byte)value1;
	Sendbuf[24] = 1;
	Sendbuf[25] = (byte)value2;
	SendData(Sendbuf);
}

should be:

void Steering2(int value1, int value2)
{
	if(value1>127)
		value1=127;
	if(value2>127)
		value2=127;
	if(value1<-127)
		value1=-127;
	if(value2<-127)
		value2=-127;
	if(value1<0)
		value1=128-value1;
	if(value2<0)
		value2=128-value2;

	Sendbuf[5] = (byte)value1;
	Sendbuf[24] = 1;
	Sendbuf[25] = (byte)value2;
	SendData(Sendbuf);
}

**Comment by Iainmon** [comment]
Thanks for pointing it out! It may take a few days for Arduino to add the patched release to the library manager.
